version: "3"

services:
  mshell-template:
    build:
      context: .
      dockerfile: Dockerfile
    image: skyscanner/mshell-template
    ports:
       - "5001:5001"
       - "5002:5002"
       - "1099:1099"
    environment:
      # JMX settings to allow use of JVisualVM
      - JAVA_JMX_PORT=1099
      - JAVA_JMX_HOST=192.168.99.100
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - $HOME/.aws/saml2aws_credentials:/home/skyscanner/.aws/credentials
